import type { Theme } from '../theme'
import { THEME_SCHEMA_VERSION } from '../theme'

/** Nord — the arctic, north-bluish dark scheme. */
export const nord: Theme = {
  version: THEME_SCHEMA_VERSION,
  id: 'nord',
  name: 'Nord',
  type: 'dark',
  builtIn: true,
  author: 'Arctic Ice Studio',
  bootBackground: '#2e3440',
  app: {
    'surface-0': '#2e3440',
    'surface-1': '#333b4a',
    'surface-2': '#3b4252',
    'surface-3': '#424b5c',
    'surface-4': '#434c5e',
    'surface-5': '#4c566a',
    'surface-6': '#556074',
    'titlebar-bg': '#2b313c',
    'canvas-bg': '#272c36',
    'canvas-bg-alt': '#2c323d',
    'grid-dot': 'rgba(216, 222, 233, 0.07)',
    'grid-line': 'rgba(216, 222, 233, 0.03)',
    'border-subtle': 'rgba(216, 222, 233, 0.06)',
    'border-strong': 'rgba(216, 222, 233, 0.12)',
    'border-focus': '#88c0d0',
    'text-primary': '#eceff4',
    'text-secondary': '#d8dee9',
    'text-muted': '#8a93a8',
    'text-inverse': '#2e3440',
    'focus-blue': '#88c0d0',
    'activity-green': '#a3be8c',
    'activity-orange': '#d08770',
    'shadow-node': 'rgba(0, 0, 0, 0.45)',
    'shadow-node-focused': 'rgba(136, 192, 208, 0.35)',
    'node-bg-active': '#2b313c',
    'node-dim-overlay': 'rgba(0, 0, 0, 0.18)',
    'scrollbar-thumb': 'rgba(216, 222, 233, 0.15)',
    'scrollbar-thumb-hover': 'rgba(216, 222, 233, 0.25)',
    'surface-hover': 'rgba(216, 222, 233, 0.06)',
    'surface-hover-strong': 'rgba(216, 222, 233, 0.12)',
    'git-added': '#a3be8c',
    'git-modified': '#ebcb8b',
    'git-deleted': '#bf616a',
    'git-untracked': '#88c0d0',
    'git-renamed': '#b48ead',
    'panel-terminal': '#6a9b7a',
    'panel-browser': '#6f8fb0',
    'panel-editor': '#b09a6a',
    'panel-git': '#b06a72',
    'panel-fileExplorer': '#6f9fb0',
    'panel-projectList': '#a89a6a',
    'panel-canvas': '#9a7fa8',
    'agent-rgb': '136 192 208',
    'agent-light-rgb': '143 188 187',
  },
  terminal: {
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#d8dee9',
    selectionBackground: '#434c5e',
    selectionForeground: '#eceff4',
    black: '#3b4252', red: '#bf616a', green: '#a3be8c', yellow: '#ebcb8b',
    blue: '#81a1c1', magenta: '#b48ead', cyan: '#88c0d0', white: '#e5e9f0',
    brightBlack: '#4c566a', brightRed: '#bf616a', brightGreen: '#a3be8c', brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1', brightMagenta: '#b48ead', brightCyan: '#8fbcbb', brightWhite: '#eceff4',
  },
  editor: {
    base: 'vs-dark',
    colors: {
      'editor.background': '#2e3440',
      'editor.foreground': '#d8dee9',
      'editorGutter.background': '#2e3440',
      'minimap.background': '#2e3440',
      'editorLineNumber.foreground': '#4c566a',
      'editorLineNumber.activeForeground': '#d8dee9',
      'editor.lineHighlightBackground': '#3b4252',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#434c5e',
      'editorCursor.foreground': '#d8dee9',
      'contrastBorder': '#00000000',
    },
    tokens: [
      { token: 'comment', foreground: '616e88', fontStyle: 'italic' },
      { token: 'keyword', foreground: '81a1c1' },
      { token: 'storage', foreground: '81a1c1' },
      { token: 'string', foreground: 'a3be8c' },
      { token: 'constant.numeric', foreground: 'b48ead' },
      { token: 'constant.language', foreground: '81a1c1' },
      { token: 'variable', foreground: 'd8dee9' },
      { token: 'variable.parameter', foreground: 'd8dee9' },
      { token: 'entity.name.function', foreground: '88c0d0' },
      { token: 'entity.name.class', foreground: '8fbcbb' },
      { token: 'entity.name.type', foreground: '8fbcbb' },
      { token: 'entity.name.tag', foreground: '81a1c1' },
      { token: 'entity.other.attribute-name', foreground: '8fbcbb' },
      { token: 'support.function', foreground: '88c0d0' },
      { token: 'type', foreground: '8fbcbb' },
      { token: 'operator', foreground: '81a1c1' },
      { token: 'regexp', foreground: 'ebcb8b' },
      { token: 'markup.heading', foreground: '88c0d0', fontStyle: 'bold' },
      { token: 'markup.bold', fontStyle: 'bold' },
      { token: 'markup.italic', fontStyle: 'italic' },
      { token: 'invalid', foreground: 'bf616a' },
    ],
  },
}
